name: Build ffmpeg-static for loongarch64

permissions: write-all

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  debian:
    name: Build for Debian
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        variant:
          - kde
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 4096
          swap-size-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up loong64 Debian container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/loong64/debian:trixie
          options: --cpus=4 --platform linux/loong64 --privileged -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt update; apt install sudo git curl wget jq -y
            git config --global --add safe.directory /work
            bash ./build-ubuntu.sh -j $(nproc)
            tar -zcvf ffmpeg-static-loongarch64.tar.gz target
            
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-static for Debian loong64
          path: ${{ github.workspace }}/ffmpeg-static-loongarch64.tar.gz
          compression-level: 0
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
